### ISSUE TITLE
shipping price showing zero

### ISSUE THREAD

**Issue by Hammadi89** [mageplaza/magento-2-multi-flat-rates#2]
I have installed this extension on my store, I have followed the instruction from user guide, after configuration i enable two flate rates with price 5 and 10 respectively but on store front it shows price equals to "0". Please help me!

**Comment by datvm231** [comment]
Hello,

It might have something to do with the cart price rules on your site.
Please check them in `Admin Panel > Marketing > Promotions > Cart Price Rules`

**Comment by Hammadi89** [comment]
Hi,

Can you please guide me, what should I do in Cart Price Rules.

**Comment by datvm231** [comment]
Please check if you have any rules that give free shipping and deactivate them.
