### ISSUE TITLE
magento 2.3.1 - cannot create new order via backend - cannot select shipping method

### ISSUE THREAD

**Issue by LouNik1984** [mageplaza/magento-2-multi-flat-rates#3]
I had this extension installed on magento 2.3.0 and it worked both on frontend and backend, then I upgraded magento to the 2.3.1. 

On magento 2.3.1 the extension works on frontend as expected but I cannot create an order from backend anymore. What I mean is: 

- go to backend of magento 2.3.1 > orders > create new order
- select customers and add a product
- try and click on "select shipping method"

What I expect is to be able to click on the link "select shipping method" and view the list of available methods to choose from

What I actually see is that the link is uncliccable.

**Comment by legendhorus** [comment]
I checked the extension on Magento 2.3.1 and saw it works well [https://prnt.sc/o7rye3](https://prnt.sc/o7rye3). Maybe your problem is due to another shipping module.

You can create a ticket in [https://mageplaza.freshdesk.com](https://mageplaza.freshdesk.com). We will help you check it

**Comment by LouNik1984** [comment]
Yes you are right, I checked again against all the extensions that I had and it turned out to be a third party extension the real culprit

**Comment by legendhorus** [comment]
Since there is no issue left. I am going to close this issue now.
If you have any further question/issue, feel free to contact us. We will be here to assist you.
