### ISSUE TITLE
automatic update not working

### ISSUE THREAD

**Issue by fabeff** [mageplaza/magento-2-multi-flat-rates#5]
Hi at all. First of all many compliments for your module, is very helpfull!
I have just a little problem. I set 4 different flat rate:

1) just Italy
2) just Europe
3) just USA and Canada
4) other Countries

For each of them I selected "hide if not available" in order to show just the right flat rate according with selected Country in the one page checkout.

I don't know why, by default, is selected "Italy" and if the customer change country the flat rate is not updating automatically. It updates only if customer click on "next step" (and user remain in the same step but with updated shipping rate).

How could I fix this issue in order to update the shipping rate at the same time that County is selected?

Attached screen record
[flat-rate.mov.zip](https://github.com/mageplaza/magento-2-multi-flat-rates/files/3713746/flat-rate.mov.zip)

Many thanks,
Fabrizio

**Comment by datvm231** [comment]
Hello,

Sorry for the delay in getting back to you. If you are still looking for the resolution, we have updated the extension recently to fix this issue. It is currently applied on develop branch.

Here is the related commit: a4f949bf099e965862fc58731554722e85943c82
